touchscreen_mmi: Mark mode_type as maybe unused
../../../../../../kernel/motorola/sm7325/drivers/input/touchscreen/touchscreen_mmi/touchscreen_mmi_gesture.c:216:16: error: unused variable 'mode_type' [-Werror,-Wunused-variable]
        unsigned char mode_type = touch_cdev->gesture_mode_type;
                      ^
1 error generated.

Change-Id: Id01d5c2286156e6ee2dd1da2bd9b9a7c9bb883bf